# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\";\n\x0e\x42ookSuggestion\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\'\n\x11SuggestionRequest\x12\x12\n\nbookTitles\x18\x01 \x03(\t\"F\n\x12SuggestionResponse\x12\x30\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x1b.suggestions.BookSuggestion2d\n\x11SuggestionService\x12O\n\x0cSuggestBooks\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKSUGGESTION']._serialized_start=34
  _globals['_BOOKSUGGESTION']._serialized_end=93
  _globals['_SUGGESTIONREQUEST']._serialized_start=95
  _globals['_SUGGESTIONREQUEST']._serialized_end=134
  _globals['_SUGGESTIONRESPONSE']._serialized_start=136
  _globals['_SUGGESTIONRESPONSE']._serialized_end=206
  _globals['_SUGGESTIONSERVICE']._serialized_start=208
  _globals['_SUGGESTIONSERVICE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
