# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05hello\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\x80\x01\n\x15\x46raudDetectionRequest\x12\x18\n\x10\x63reditCardNumber\x18\x01 \x01(\t\x12 \n\x18\x63reditCardExpirationDate\x18\x02 \x01(\t\x12\x15\n\rcreditCardCVV\x18\x03 \x01(\t\x12\x14\n\x0c\x64iscountCode\x18\x04 \x01(\t\"K\n\x16\x46raudDetectionResponse\x12\x0f\n\x07isFraud\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2E\n\x0cHelloService\x12\x35\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse2c\n\x15\x46raudDetectionService\x12J\n\x0b\x44\x65tectFraud\x12\x1c.hello.FraudDetectionRequest\x1a\x1d.hello.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=60
  _globals['_HELLORESPONSE']._serialized_start=62
  _globals['_HELLORESPONSE']._serialized_end=95
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=98
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=226
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=228
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=303
  _globals['_HELLOSERVICE']._serialized_start=305
  _globals['_HELLOSERVICE']._serialized_end=374
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=376
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
