# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19suggestions_service.proto\x12\x05hello\"(\n\x11SuggestionRequest\x12\x13\n\x0b\x62ook_titles\x18\x01 \x03(\t\".\n\x12SuggestionResponse\x12\x18\n\x10\x62ook_suggestions\x18\x01 \x03(\t2S\n\x11SuggestionService\x12>\n\x07Suggest\x12\x18.hello.SuggestionRequest\x1a\x19.hello.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONREQUEST']._serialized_start=36
  _globals['_SUGGESTIONREQUEST']._serialized_end=76
  _globals['_SUGGESTIONRESPONSE']._serialized_start=78
  _globals['_SUGGESTIONRESPONSE']._serialized_end=124
  _globals['_SUGGESTIONSERVICE']._serialized_start=126
  _globals['_SUGGESTIONSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
